blogtest/config/routes.rb
Rails.application.routes.draw do
  get 'tagshow/index'

  devise_for :users
  #get 'pages/index'

  #get 'pages/show'

  resources :pages do
  	resources :comments do 
	end
  end




root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blogtest/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :page
end

blogtest/app/models/page.rb
class Page < ApplicationRecord
	default_scope -> {order(updated_at: :desc)}
	has_many :comments 
end

blogtest/app/models/tag.rb
class Tag < ApplicationRecord

belongs_to :Page

end

blogtest/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blogtest/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

blogtest/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
	@page=Page.find(params[:page_id])
	@comment=@page.comments.create(comment_params)
	redirect_to page_path(@page.id)

end


def destroy
	@page=Page.find(params[:page_id])
	@comment=@page.comments.find(params[:id])

	@comment.destroy
	redirect_to page_path(@page.id)
end




private 
	def comment_params
		params[:comment].permit(:body)
	end

end

blogtest/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@page=Page.all

	if user_signed_in?
		@user=current_user.email
	end
	#if Page.count>0

	
	@counter=Page.count
	ids=REDIS.zrevrange "pages",0,2, withscores: true
	
	@ids=ids
	@ids_inv=ids.transpose
	@flag=!@ids_inv.empty?
	
	if @flag 
		@pages=@ids_inv[0].map{|id|Page.find(id)}
	end	
	
	
  end

  def show
	@page=Page.find(params[:id])
	if user_signed_in?
		@user=current_user.email
	end
	#REDIS.zincrby "pages/daily/#{Date.today.to_s}",1,@page.id
	REDIS.zincrby "pages",1,@page.id
	ids=REDIS.zrevrange "pages",0,2, withscores: true
	#@pv=REDIS.get "pages/daily/#{Date.today.to_s}/#{@page.id}"
	
	#@scores=scores
	@ids=ids
	@ids_inv=ids.transpose
	@flag=!@ids_inv.empty?
	
	#@pages=Page.where(id: @ids_inv[0])
	if @flag
		@pages=@ids_inv[0].map{|id|Page.find(id)}
	end
  end


  def new
  	@page=Page.new
  end




	def create
		@page=Page.new(page_params)
		@page.attributes={author: current_user.email}
		@page.save
		redirect_to root_path
	end


	def destroy
		@page=Page.find(params[:id])
		@page.destroy
		REDIS.zrem "pages" ,@page.id
		redirect_to root_path
	end


	def edit
		@page=Page.find(params[:id])
	end


	def update
		@page=Page.find(params[:id])
		@page.update(page_params)
		redirect_to root_path	
	end
private
	def page_params
		params[:page].permit(:title,:body)
	end
		


end

blogtest/app/controllers/tags_controller.rb
class TagsController < ApplicationController

def new
end


def create
	@page=Page.find(params[:page_id])
	@tag=@page.tags.create(tag_params)
end










private
	def tag_params
		params[:tag.id].permit(:name)
	end



end

blogtest/app/controllers/tagshow_controller.rb
class TagshowController < ApplicationController
  def index
	@page=Page
	@comment=Comment.all.includes(:page)
	@commentname=Comment.pluck(:body).uniq
	
	if user_signed_in?
		@user=current_user.email
	end


	@counter=Page.count
	ids=REDIS.zrevrange "pages",0,2,withscores: true

	@ids=ids
	@ids_inv=ids.transpose
	@flag=!@ids_inv.empty?

	if @flag
		@pages=@ids_inv[0].map{|id|Page.find(id)}
	end


  end

end

blogtest/app/helpers/articles_helper.rb
module ArticlesHelper
end

blogtest/app/helpers/comments_helper.rb
module CommentsHelper
end

blogtest/app/helpers/tags_helper.rb
module TagsHelper
end

blogtest/app/helpers/tagshow_helper.rb
module TagshowHelper
end

blogtest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogtest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>





  <body>


<!--
		<header>
			<nav>
				<!% if user_signed_in?%>
				<strong><!%= link_to current_user.email, pages_path %></strong>
				<!%= link_to 'プロフィール変更', edit_user_registration_path %>
				<!%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
			<!% else %>
				<!%= link_to 'サインアップ', new_user_registration_path %>	
				<!%= link_to 'ログイン', new_user_session_path %>						    
				<!% end %>																					</nav>		
		</header>


-->



<!--
<p class="notice"><!%= notice %></p>
	<p class="alert"><!%= alert %></p>
-->


    <%= yield %>
  </body>
</html>

blogtest/app/views/pages/_form.html.erb
<div id="article_wrap">
    <!form class="edit_article" id="edit_article_55" action="/articles/55" accept-charset="UTF-8" method="post"><!input name="utf8" type="hidden" value="&#x2713;" /><!input type="hidden" name="_method" value="patch" /><!input type="hidden" name="authenticity_token" value="WSpNZ4EIJBX7s3WGOfIjj5nWgjTQ4uYcFrvvvXe6x1NojCIkWDPqIeZ4AtmYJqjgLI2mpx7efuLBwUvpoUuTeQ==" />
        タイトル<br>
        <!input type="text" value="記事１" name="article[title]" id="article_title" />

		<%=form_for @page do |f|%>
		<%=f.text_field :title%>
        <br><br>
        
        記事内容<br>
        <!textarea name="article[content]" id="article_content">

		<%=f.text_area :body%>
        <br><br>
        
        <!input type="submit" name="commit" value="Update Article" />
        <%=f.submit%>
		<%end%>
        <br><br>
        
<!/form></div>
<footer>
    <div id="footer_inner">
        <p>Copyright RailsCamp 2015 All Rights Reserved</p>
    </div>
</footer>


</body>
</html>

blogtest/app/views/pages/_side.html.erb
<div id="sidebar">
            
        <h2>★PV数ランキング</h2>
        <ul>
			<%count=0%>
			<!%= @ids_inv.inspect%>
			<!%= @tag.inspect%>
			<%if @tag%> 
            <%@pages.each do |f|%>
            <li>
				<!%=count%>
                <%=link_to f.title,page_path(f.id)%><%="("+@ids_inv[1][count].to_i.to_s+"PV"+")"%>
				<%count+=1%>
            </li>
            <%end%>
			<%end%>

        </ul>
    </div>
    <div class="clear"></div>
</div>

blogtest/app/views/pages/edit.html.erb
<%= render :partial => 'header'%>
<%= render :partial=>'form'%>

blogtest/app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta charset="UTF-8">
    <title>Rails Camp Blog</title>
    <link rel="stylesheet" href="style.css" type="text/css" media="screen">
</head>
<body>




<%= render :partial => "header"%>




<div id="main">
    <!img src="main-img.jpg">
	<%= image_tag 'main-img.jpg'%>
</div>


<div id="article_wrap">

    <div id="article_list">


		

		<% @page.each do |page|%>

		<div>
			<h2><%= link_to page.title,page_path(page.id) %></h2>
			<p><%= page.updated_at.to_s(:updated_at)%></p>
			<p><a>
			<%if user_signed_in?%>

			<% if page.author==@user%>
			<%=link_to '編集',edit_page_path(page.id) %>
			<%=link_to '削除',page_path(page.id),method: :delete %>
			<%=link_to 'タグ追加', page_path(page.id)%>
			<%end%>
			<%end%>
        	</a></p>
			<p><a>
			[タグ]
			<% page.comments.each do |comment|%>
				<%=comment.body%>
			<%end%>
			</a></p>

		
		</div>
		<%end%>


		
		<h2>
		<%=link_to "タグ一覧ページを表示", tagshow_index_path%>
		</h2>
    </div>

	<%= render :partial => 'side'%>
<footer>
    <div id="footer_inner">
        <p>Copyright RailsCamp 2015 All Rights Reserved</p>
    </div>
</footer>

</body>
</html>

blogtest/app/views/pages/index.html_test.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

blogtest/app/views/pages/new.html.erb
<%= render :partial =>"header"%>

<%= render :partial => "form"%>

blogtest/app/views/pages/show.html.erb
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta charset="UTF-8">
    <title>Rails Camp Blog</title>
    <link rel="stylesheet" href="style.css" type="text/css" media="screen">
</head>
<body>

<%= render :partial => 'header'%>


<div id="title">
    <div>
		<p><%=@page.updated_at.to_s(:updated_at)%> 書いた人:<%=@page.author%></p>
		

        <h1><%=@page.title%></h1>
    </div>
</div>

<div id="article_wrap">

    <div id="content">
		<%=@page.body%>
		<h3>
		<%="[タグ]"%>
		</h3>
		<!%@page.comments.all.includes(:page).each do |comment|%>
		<%@page.comments.each do |comment|%>
		<p>
		<!%if comment.body=="aaa"%>
		<%=comment.body%>

		<%=link_to "[削除]",page_comment_path(@page,comment.id),method: :delete%>
		<!%end%>
		</p>
		<%end%>
	<h3>
		<%= form_for [@page,@page.comments.build] do |f|%>
		<%=f.label "タグ追加"%>
		<%=f.text_field :body%>
		<%=f.submit%>
		<%end%>



	</h3>

	</div>


	</div>




<%=render :partial => 'side'%>

<footer>
    <div id="footer_inner">
        <p>Copyright RailsCamp 2015 All Rights Reserved</p>
    </div>
</footer>

</body>
</html>